services:
  traefik:
    image: traefik:v3.6
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"

      - "--providers.docker.network=proxy"
      - "--entryPoints.web.address=:80"
      - "--entryPoints.recruiter.address=:8083"

      - "--api.dashboard=true"
      - "--api.insecure=true"

      - "--log.level=INFO"
    ports:
      - "80:80"
      - "8083:8083"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - proxy
    restart: unless-stopped

  candidate-web:
    build:
      context: .
      dockerfile: apps/candidate-web/Dockerfile
    labels:
      # Enable Traefik for this service
      - "traefik.enable=true"
      # Define router
      - "traefik.http.routers.candidate.entrypoints=web"
      - "traefik.http.routers.candidate.rule=Host(`109.73.199.198`)"
      # Define service
      - "traefik.http.services.candidate.loadbalancer.server.port=80"
    networks:
      - proxy
    depends_on:
      traefik:
        condition: service_started
    restart: unless-stopped
    env_file:
      - .env

  recruiter-web:
    build:
      context: .
      dockerfile: apps/recruiter-web/Dockerfile
    labels:
      # Enable Traefik for this service
      - "traefik.enable=true"
      # Define router
      - "traefik.http.routers.recruiter.entrypoints=recruiter"
      - "traefik.http.routers.recruiter.rule=Host(`109.73.199.198`)"
      # Define service
      - "traefik.http.services.recruiter.loadbalancer.server.port=80"
    networks:
      - proxy
    depends_on:
      traefik:
        condition: service_started
    restart: unless-stopped
    env_file:
      - .env
networks:
  proxy:
    driver: bridge